# Generated by Django 3.1.7 on 2021-03-04 23:55

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdresPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("b0a7635f-d1c2-4e70-bc56-6a112b314b32"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("adres", models.CharField(max_length=15)),
                ("geometry", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id_simc", models.IntegerField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PostCode",
            fields=[
                (
                    "code",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Street",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street_id", models.IntegerField()),
                ("street", models.CharField(max_length=100)),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="archive_manager.city",
                    ),
                ),
            ],
            options={
                "unique_together": {("street_id", "city")},
            },
        ),
        migrations.CreateModel(
            name="Buildings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("029d552b-3242-413b-963d-9d6df8f0c7b8"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("age", models.IntegerField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        null=True, srid=4326
                    ),
                ),
                (
                    "adress",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="archive_manager.adrespoint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="adrespoint",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="archive_manager.city",
            ),
        ),
        migrations.AddField(
            model_name="adrespoint",
            name="post_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="archive_manager.postcode",
            ),
        ),
        migrations.AddField(
            model_name="adrespoint",
            name="street",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="archive_manager.street",
            ),
        ),
    ]
