# Generated by Django 3.1.3 on 2021-01-19 00:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddresPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('93b17706-6818-4040-b45e-b970d369506a'), editable=False, primary_key=True, serialize=False)),
                ('adres', models.CharField(max_length=15)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_simc', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostCode',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_id', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_manager.city')),
            ],
            options={
                'unique_together': {('street_id', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3ac4ce01-90a9-41b3-86d0-5a784804f973'), editable=False, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('adress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_manager.addrespoint')),
            ],
        ),
        migrations.AddField(
            model_name='addrespoint',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_manager.city'),
        ),
        migrations.AddField(
            model_name='addrespoint',
            name='post_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_manager.postcode'),
        ),
        migrations.AddField(
            model_name='addrespoint',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_manager.street'),
        ),
    ]
