# Generated by Django 3.1.7 on 2021-03-04 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('archive_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adrespoint',
            name='id',
            field=models.UUIDField(default=uuid.UUID('05c1be95-dc62-4f0c-9061-ea849b6d17d1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8f13e112-9d06-47ca-9353-00ee1b09008b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
