# Generated by Django 3.1.3 on 2021-01-24 14:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive_manager", "0002_auto_20210123_2119"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addrespoint",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f95769f4-1f61-4446-8705-270fc8f731f3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="buildings",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="buildings",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8b071b66-a7ec-4c89-adc9-ba71eac69e78"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
