# Generated by Django 3.1.3 on 2021-01-24 14:04

import uuid

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive_manager", "0003_auto_20210124_1402"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addrespoint",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ff3e12f3-6678-4c34-9507-7a91487af6b6"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="buildings",
            name="geometry",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="buildings",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3c231605-b685-4e1e-80b9-3796f8d512df"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
