# Generated by Django 3.1.6 on 2021-02-21 00:51

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive_manager", "0004_auto_20210124_1404"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addrespoint",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("93ce05a7-5b6e-4617-b4fa-1550bbb56ca2"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="buildings",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4cbdc488-90cb-4190-88d6-686e4d9a5584"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
